path: /content/mixed_2_classes # dataset root dir
train: train/images # train images (relative to 'path')
test: test/images # test images (relative to 'path')
val: valid/images # val images (relative to 'path')

# Classes
names:
  1: Oskar
  0: Dog
